# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMBL_ABR_STM', '0002_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_australian',
            field=models.BooleanField(default=False),
        ),
    ]
