# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMBL_ABR_STM', '0003_source_is_australian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.CharField(max_length=300)),
                ('source_url', models.CharField(max_length=300)),
            ],
        ),
    ]
