# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMBL_ABR_STM', '0004_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='emails',
            new_name='email',
        ),
    ]
